//FETCH DATA FLAGS
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const UPDATE_DATA_START = 'UPDATE_DATA_START';
//SIGNIN APIS
export const GET_VERIFICATION_CODE_SUCCESS = 'GET_VERIFICATION_CODE_SUCCESS';
export const CHECK_VERIFICATION_CODE_SUCCESS = 'CHECK_VERIFICATION_CODE_SUCCESS';
export const USER_SIGN_OUT_SUCCESS = 'USER_SIGN_OUT_SUCCESS';
//USER APIS
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_ADDRESS_SUCCESS = 'GET_USER_ADDRESS_SUCCESS';
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS';
export const POST_USER_ADDRESS_SUCCESS = 'POST_USER_ADDRESS_SUCCESS';
//TASK APIS
export const GET_TASK_TYPE_LIST_SUCCESS = 'GET_TASK_TYPE_LIST_SUCCESS';
export const GET_TASK_POOL_SUCCESS = 'GET_TASK_POOL_SUCCESS';
export const GET_USER_INCOMPLETED_TASK_SUCCESS = 'GET_USER_INCOMPLETED_TASK_SUCCESS';
export const GET_USER_COMPLETED_TASK_SUCCESS = 'GET_USER_COMPLETED_TASK_SUCCESS';
export const GET_TASK_DETAIL_SUCCESS = 'GET_TASK_DETAIL_SUCCESS';
export const CHANGE_TASK_STATE_SUCCESS = 'CHANGE_TASK_STATE_SUCCESS';
export const CREATE_NEW_TASK_SUCCESS = 'CREATE_NEW_TASK_SUCCESS';


